// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::db_vector_3_type::DbVector3;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Collider {
    pub id: u32,
    pub positions: Vec<DbVector3>,
    pub indices: Vec<DbVector3>,
    pub name: String,
}

impl __sdk::InModule for Collider {
    type Module = super::RemoteModule;
}
