// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::input_state_type::InputState;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdatePlayerInputArgs {
    pub input: InputState,
    pub rotation: f32,
}

impl From<UpdatePlayerInputArgs> for super::Reducer {
    fn from(args: UpdatePlayerInputArgs) -> Self {
        Self::UpdatePlayerInput {
            input: args.input,
            rotation: args.rotation,
        }
    }
}

impl __sdk::InModule for UpdatePlayerInputArgs {
    type Module = super::RemoteModule;
}

pub struct UpdatePlayerInputCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_player_input`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_player_input {
    /// Request that the remote module invoke the reducer `update_player_input` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_update_player_input`] callbacks.
    fn update_player_input(&self, input: InputState, rotation: f32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `update_player_input`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`UpdatePlayerInputCallbackId`] can be passed to [`Self::remove_on_update_player_input`]
    /// to cancel the callback.
    fn on_update_player_input(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &InputState, &f32) + Send + 'static,
    ) -> UpdatePlayerInputCallbackId;
    /// Cancel a callback previously registered by [`Self::on_update_player_input`],
    /// causing it not to run in the future.
    fn remove_on_update_player_input(&self, callback: UpdatePlayerInputCallbackId);
}

impl update_player_input for super::RemoteReducers {
    fn update_player_input(&self, input: InputState, rotation: f32) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "update_player_input",
            UpdatePlayerInputArgs { input, rotation },
        )
    }
    fn on_update_player_input(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &InputState, &f32) + Send + 'static,
    ) -> UpdatePlayerInputCallbackId {
        UpdatePlayerInputCallbackId(self.imp.on_reducer(
            "update_player_input",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::UpdatePlayerInput { input, rotation },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, input, rotation)
            }),
        ))
    }
    fn remove_on_update_player_input(&self, callback: UpdatePlayerInputCallbackId) {
        self.imp
            .remove_on_reducer("update_player_input", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `update_player_input`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_update_player_input {
    /// Set the call-reducer flags for the reducer `update_player_input` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn update_player_input(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_update_player_input for super::SetReducerFlags {
    fn update_player_input(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("update_player_input", flags);
    }
}
