// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

import { DbVector3 as __DbVector3 } from "./db_vector_3_type";

export type UploadBody = {
  points: __DbVector3[],
  indices: __DbVector3[],
  name: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace UploadBody {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("points", AlgebraicType.createArrayType(__DbVector3.getTypeScriptAlgebraicType())),
      new ProductTypeElement("indices", AlgebraicType.createArrayType(__DbVector3.getTypeScriptAlgebraicType())),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: UploadBody): void {
    UploadBody.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): UploadBody {
    return UploadBody.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

